# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 02:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cate_Type', models.CharField(max_length=50)),
                ('Cate_Desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trans_Desc', models.TextField()),
                ('Trans_Date', models.DateTimeField()),
                ('Trans_Type', models.CharField(max_length=50)),
                ('Trans_Loc', models.CharField(max_length=150)),
                ('Trans_Amnt', models.DecimalField(decimal_places=2, default=0, max_digits=150)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
